### ISSUE TITLE
Using website GPT4 plus user interface or API

### ISSUE THREAD

**Issue by turtoe** [caoyunkang/GPT4V-for-Generic-Anomaly-Detection#4]
Thank you for the great work. I wonder how you use the GPT4V model, since the website user interface only shows GPT4 instead of GPT4V, did you use the API for the experiments? Will be glad to hear from you, thank you

**Comment by caoyunkang** [comment]
Hi! Thanks for your interest. The web interface does provide GPT4V. Please reach out to me if you have any other questions.
